### ISSUE TITLE
[Task] Add build support for `Application`, `Script`, `Library`, `Development Library` package types with `paket build`

### ISSUE THREAD

**Issue by eminfedar** [pardus-topluluk/paket#8]
**Description:**
Create a paket regarding to the paket type of these:
- `PackageType::Application`
- `PackageType::Script`
- `PackageType::Library`
- `PackageType::DevelopmentLibrary`

**TODO:** These package types have custom fields. `Application` & `Script` types have `executable` stores the binary which makes paket manage application and script pakets more powerful. (will work on these fields, program files which stored on /usr/share for scripting files? etc.) Libraries also should be powerful to work on. paket should know if it is an archive .a or .so file only etc.

**Acceptance Criteria:**
* [ ] Local paket can be installed successfully.
* [ ] Installed pakets are stored in `/var` folder.
* [ ] Upgrading or Downgrading for same package.
* [ ] SHA256SUM check before installation
* [ ] Different installation tactics for different PackageTypes.
* [ ] Tests are passing.
* [ ] Documentations on every struct, property and function is written with `///`. There should be a description and a small example usage.

---
**Implementation Details:**

```rust
// Some example code about how it will work
```
